### ISSUE TITLE
Cannot setup the plugins

### ISSUE THREAD

**Issue by werewolfdev** [carla-simulator/traffic-generation-editor#15]
Trying to use this tool for editing scenarios.

I get this error while trying to load Traffic generation editor
ImportError: libpugixml.so.1: cannot open shared object file: No such file or directory 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/schemba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/traffic-generation-editor-main/__init__.py", line 21, in classFactory
    from .carla_scenario_editor import OSC_Generator    # pylint: disable=import-outside-toplevel,import-error
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/schemba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/traffic-generation-editor-main/carla_scenario_editor.py", line 22, in 
    from .osc_generator.add_vehicles import AddVehiclesDockWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/schemba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/traffic-generation-editor-main/osc_generator/add_vehicles.py", line 21, in 
    import ad_map_access as ad
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/schemba/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ad_map_access_qgis/ad_map_access/__init__.py", line 17, in 
    from ad_map_access_python36_module import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: libpugixml.so.1: cannot open shared object file: No such file or directory

I get this error  when trying to import CARLA AD Map Plugin

ModuleNotFoundError: No module named 'map-2' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'map-2'

Any comments would be appreciated.

**Comment by fabianoboril** [comment]
Hi,

the first error seems to be rooted in the map library, most likely you do not have pugixml installed, do you?

**Comment by werewolfdev** [comment]
Hi @fabianoboril tahnks for the reply. I havent installed pugixml. Will try installing now

**Comment by werewolfdev** [comment]
Hi @fabianoboril When I try to load ad_map_access_qgis I get no module named ad_map_access error and while trying to load traffic-generation-editor i get nothe same error. CAn you let me know what i myt be doing missing out here

**Comment by fabianoboril** [comment]
As the README states, you have to install the ad-map-access Plugin for QGIS:
![image](https://user-images.githubusercontent.com/26405660/134289107-e23aefea-8f4c-4674-ae37-499fd136b0ba.png)

You can find the instructions on how to do that here:
https://ad-map-access.readthedocs.io/en/latest/ad_map_access_qgis/ad_map_access_qgis/

**Comment by werewolfdev** [comment]
Thanks . I havent seen this step of trying to pip install from bash. However it leads to this error: Collecting ad-map-access
  Could not find a version that satisfies the requirement ad-map-access (from versions: )
No matching distribution found for ad-map-access
My QGIS version is 3.16 and Iam have downloaded the zip file of 2.5.1 of ad_map_Access_qgis.zip. Am I doing something wrong

**Comment by werewolfdev** [comment]
@fabianoboril Thanks . I havent seen this step of trying to pip install from bash. However it leads to this error: Collecting ad-map-access
Could not find a version that satisfies the requirement ad-map-access (from versions: )
No matching distribution found for ad-map-access
My QGIS version is 3.16 and Iam have downloaded the zip file of 2.5.1 of ad_map_Access_qgis.zip. Am I doing something wrong

**Comment by werewolfdev** [comment]
@fabianoboril I updated pip to latest version and both the plugins are loaded now .Sorry for the inconvenience due to errors from my side .

**Comment by nda97531** [comment]
ad-map-access can be installed via pip but I still get this error when installing traffic-generation-editor in QGIS.
Please help :( 
![image](https://user-images.githubusercontent.com/42064053/148332611-183e3c73-de37-4e4b-8212-9120d36ff391.png)
