### ISSUE TITLE
Error while installing the plugin from zip

### ISSUE THREAD

**Issue by Dan-A22** [carla-simulator/traffic-generation-editor#29]
Hi everybody. I was following the installation guide and when I tried to do the "install from zip" part I faced the following error:

Couldn't load plugin 'traffic-generation-editor-main' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'ad_map_access' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.28.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/99660813/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\traffic-generation-editor-main\__init__.py", line 21, in classFactory
    from .carla_scenario_editor import OSC_Generator    # pylint: disable=import-outside-toplevel,import-error
  File "C:\PROGRA~1/QGIS 3.28.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/99660813/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\traffic-generation-editor-main\carla_scenario_editor.py", line 22, in 
    from .osc_generator.add_vehicles import AddVehiclesDockWidget
  File "C:\PROGRA~1/QGIS 3.28.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/99660813/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\traffic-generation-editor-main\osc_generator\add_vehicles.py", line 21, in 
    import ad_map_access as ad
  File "C:\PROGRA~1/QGIS 3.28.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ad_map_access'

Does anyone know how can I fix this problem? any help is much appreciated!

**Comment by ccysway** [comment]
Hi,
   You need install the [CARLA AD Map plugin](https://github.com/carla-simulator/map/releases) to qgis first.
![map_plugin](https://user-images.githubusercontent.com/89178404/231635758-cab3f07d-19e5-4e3e-9dfc-436869afeb15.png)
