### ISSUE TITLE
ModuleNotFoundError: No module named 'traffic-generation-editor-1' 

### ISSUE THREAD

**Issue by heshanchuan** [carla-simulator/traffic-generation-editor#33]
**when I install plugin "traffic-generation-editor" by following way:**

from plugins menu (Plugins > Manage and Install Plugins > Install from ZIP), choose the zip file that was previously downloaded.

**Some errors have occurred: **

Couldn't load plugin 'traffic-generation-editor-1.1.0' 

ModuleNotFoundError: No module named 'traffic-generation-editor-1' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'traffic-generation-editor-1'

**Comment by heshanchuan** [comment]
Hello everyone, I have solved this problem.

Download the **traffic-generation-editor** as a zip file in GitHub (Code > Download ZIP).

by this way (this is the newest version, it is ok): 
![image](https://github.com/carla-simulator/traffic-generation-editor/assets/45147572/7f5fe9e9-9e78-4fea-9f8d-b59ee7c3e740)
